/**
 * Major Arcana data - 22 archetypes with Golden Dawn correspondences.
 *
 * Primary source: Golden Dawn tradition (most widely adopted, best documented)
 * Hebrew letters: Sepher Yetzirah via Golden Dawn arrangement
 * Confidence levels: Based on cross-traditional agreement
 *
 * @see docs/plans/archetype-correspondences-research.md
 */

import type { Archetype, ArchetypeSlug } from "./types";

/**
 * Complete data for all 22 Major Arcana
 */
export const ARCHETYPES: Record<ArchetypeSlug, Archetype> = {
  "the-fool": {
    slug: "the-fool",
    name: "The Fool",
    number: 0,
    romanNumeral: "0",
    hebrewLetter: {
      letter: "\u05D0",
      name: "Aleph",
      meaning: "Ox",
      value: 1,
    },
    attributionType: "element",
    primaryAttribution: "Air",
    element: "air",
    planet: null,
    zodiac: null,
    confidence: "high",
    keywords: ["beginnings", "innocence", "spontaneity", "free spirit", "leap of faith"],
    jungianArchetype: "The Innocent",
    description: "The Fool represents unlimited potential, new beginnings, and the courage to take a leap into the unknown. Standing at the edge of a cliff, the Fool embodies pure spirit before it manifests in the material world.",
    uprightMeanings: ["new beginnings", "innocence", "spontaneity", "free spirit", "adventure"],
    reversedMeanings: ["recklessness", "fear of change", "naivety", "holding back"],
    imagePath: "/images/archetypes/00-the-fool.jpg",
  },

  "the-magician": {
    slug: "the-magician",
    name: "The Magician",
    number: 1,
    romanNumeral: "I",
    hebrewLetter: {
      letter: "\u05D1",
      name: "Beth",
      meaning: "House",
      value: 2,
    },
    attributionType: "planet",
    primaryAttribution: "Mercury",
    element: null,
    planet: "mercury",
    zodiac: null,
    confidence: "very-high",
    keywords: ["manifestation", "willpower", "skill", "concentration", "resourcefulness"],
    jungianArchetype: "The Magician",
    description: "The Magician channels divine energy into the material world. With all four elements at his disposal, he represents the power to manifest intentions through focused will and mastery of communication.",
    uprightMeanings: ["manifestation", "power", "action", "resourcefulness", "skill"],
    reversedMeanings: ["manipulation", "poor planning", "untapped talents", "deception"],
    imagePath: "/images/archetypes/01-the-magician.jpg",
  },

  "the-high-priestess": {
    slug: "the-high-priestess",
    name: "The High Priestess",
    number: 2,
    romanNumeral: "II",
    hebrewLetter: {
      letter: "\u05D2",
      name: "Gimel",
      meaning: "Camel",
      value: 3,
    },
    attributionType: "planet",
    primaryAttribution: "Moon",
    element: null,
    planet: "moon",
    zodiac: null,
    confidence: "very-high",
    keywords: ["intuition", "mystery", "subconscious", "inner knowledge", "divine feminine"],
    jungianArchetype: "The High Priestess",
    description: "The High Priestess guards the threshold between the conscious and unconscious. She represents intuition, hidden knowledge, and the deep wisdom that comes from turning inward.",
    uprightMeanings: ["intuition", "sacred knowledge", "mystery", "subconscious mind"],
    reversedMeanings: ["secrets", "disconnection from intuition", "withdrawal", "silence"],
    imagePath: "/images/archetypes/02-the-high-priestess.jpg",
  },

  "the-empress": {
    slug: "the-empress",
    name: "The Empress",
    number: 3,
    romanNumeral: "III",
    hebrewLetter: {
      letter: "\u05D3",
      name: "Daleth",
      meaning: "Door",
      value: 4,
    },
    attributionType: "planet",
    primaryAttribution: "Venus",
    element: null,
    planet: "venus",
    zodiac: null,
    confidence: "very-high",
    keywords: ["fertility", "abundance", "nurturing", "beauty", "nature"],
    jungianArchetype: "The Great Mother",
    description: "The Empress embodies the creative force of nature, fertility, and abundance. She represents the nurturing aspect of the divine feminine and the power to bring ideas into physical form.",
    uprightMeanings: ["femininity", "beauty", "nature", "nurturing", "abundance"],
    reversedMeanings: ["creative block", "dependence", "smothering", "emptiness"],
    imagePath: "/images/archetypes/03-the-empress.jpg",
  },

  "the-emperor": {
    slug: "the-emperor",
    name: "The Emperor",
    number: 4,
    romanNumeral: "IV",
    hebrewLetter: {
      letter: "\u05D4",
      name: "Heh",
      meaning: "Window",
      value: 5,
    },
    attributionType: "zodiac",
    primaryAttribution: "Aries",
    element: "fire",
    planet: null,
    zodiac: "aries",
    confidence: "high",
    keywords: ["authority", "structure", "control", "fatherhood", "stability"],
    jungianArchetype: "The Father",
    description: "The Emperor represents order, authority, and the structuring principle. As the father figure of the Tarot, he establishes boundaries and creates stability through disciplined leadership.",
    uprightMeanings: ["authority", "structure", "control", "fatherhood", "solid foundation"],
    reversedMeanings: ["domination", "rigidity", "lack of discipline", "inflexibility"],
    imagePath: "/images/archetypes/04-the-emperor.jpg",
  },

  "the-hierophant": {
    slug: "the-hierophant",
    name: "The Hierophant",
    number: 5,
    romanNumeral: "V",
    hebrewLetter: {
      letter: "\u05D5",
      name: "Vav",
      meaning: "Nail/Hook",
      value: 6,
    },
    attributionType: "zodiac",
    primaryAttribution: "Taurus",
    element: "earth",
    planet: null,
    zodiac: "taurus",
    confidence: "high",
    keywords: ["tradition", "spiritual wisdom", "conformity", "institutions", "teaching"],
    jungianArchetype: "The Sage",
    description: "The Hierophant bridges heaven and earth as the keeper of sacred traditions. He represents spiritual authority, formal learning, and the transmission of wisdom through established institutions.",
    uprightMeanings: ["spiritual wisdom", "tradition", "conformity", "institutions", "mentorship"],
    reversedMeanings: ["personal beliefs", "freedom", "challenging tradition", "unconventional"],
    imagePath: "/images/archetypes/05-the-hierophant.jpg",
  },

  "the-lovers": {
    slug: "the-lovers",
    name: "The Lovers",
    number: 6,
    romanNumeral: "VI",
    hebrewLetter: {
      letter: "\u05D6",
      name: "Zayin",
      meaning: "Sword",
      value: 7,
    },
    attributionType: "zodiac",
    primaryAttribution: "Gemini",
    element: "air",
    planet: null,
    zodiac: "gemini",
    confidence: "high",
    keywords: ["love", "harmony", "choices", "relationships", "values alignment"],
    jungianArchetype: "The Anima/Animus",
    description: "The Lovers represent choice, partnership, and the harmonizing of opposites. Beyond romantic love, this card speaks to alignment with one's values and the integration of duality.",
    uprightMeanings: ["love", "harmony", "relationships", "values alignment", "choices"],
    reversedMeanings: ["disharmony", "imbalance", "misalignment", "bad choices"],
    imagePath: "/images/archetypes/06-the-lovers.jpg",
  },

  "the-chariot": {
    slug: "the-chariot",
    name: "The Chariot",
    number: 7,
    romanNumeral: "VII",
    hebrewLetter: {
      letter: "\u05D7",
      name: "Cheth",
      meaning: "Fence",
      value: 8,
    },
    attributionType: "zodiac",
    primaryAttribution: "Cancer",
    element: "water",
    planet: null,
    zodiac: "cancer",
    confidence: "moderate",
    keywords: ["willpower", "determination", "success", "control", "victory"],
    jungianArchetype: "The Hero",
    description: "The Chariot represents the triumph of will over obstacles. The charioteer harnesses opposing forces through determination, moving forward with confidence and self-mastery.",
    uprightMeanings: ["control", "willpower", "success", "determination", "direction"],
    reversedMeanings: ["lack of control", "opposition", "aggression", "obstacles"],
    imagePath: "/images/archetypes/07-the-chariot.jpg",
  },

  strength: {
    slug: "strength",
    name: "Strength",
    number: 8,
    romanNumeral: "VIII",
    hebrewLetter: {
      letter: "\u05D8",
      name: "Teth",
      meaning: "Serpent",
      value: 9,
    },
    attributionType: "zodiac",
    primaryAttribution: "Leo",
    element: "fire",
    planet: null,
    zodiac: "leo",
    confidence: "high",
    keywords: ["courage", "inner strength", "compassion", "patience", "influence"],
    jungianArchetype: "The Self",
    description: "Strength represents the power of gentle persuasion and inner fortitude. The woman taming the lion shows that true strength comes not from force but from courage, patience, and compassion.",
    uprightMeanings: ["strength", "courage", "persuasion", "influence", "compassion"],
    reversedMeanings: ["self-doubt", "weakness", "raw emotion", "insecurity"],
    imagePath: "/images/archetypes/08-strength.jpg",
  },

  "the-hermit": {
    slug: "the-hermit",
    name: "The Hermit",
    number: 9,
    romanNumeral: "IX",
    hebrewLetter: {
      letter: "\u05D9",
      name: "Yod",
      meaning: "Hand",
      value: 10,
    },
    attributionType: "zodiac",
    primaryAttribution: "Virgo",
    element: "earth",
    planet: null,
    zodiac: "virgo",
    confidence: "high",
    keywords: ["introspection", "solitude", "inner guidance", "wisdom", "searching"],
    jungianArchetype: "The Wise Old Man",
    description: "The Hermit walks alone, seeking truth through inner contemplation. His lantern illuminates the path for those who follow, representing the wisdom gained through solitary reflection.",
    uprightMeanings: ["soul-searching", "introspection", "guidance", "solitude", "inner wisdom"],
    reversedMeanings: ["isolation", "loneliness", "withdrawal", "lost"],
    imagePath: "/images/archetypes/09-the-hermit.jpg",
  },

  "wheel-of-fortune": {
    slug: "wheel-of-fortune",
    name: "Wheel of Fortune",
    number: 10,
    romanNumeral: "X",
    hebrewLetter: {
      letter: "\u05DB",
      name: "Kaph",
      meaning: "Palm of Hand",
      value: 20,
    },
    attributionType: "planet",
    primaryAttribution: "Jupiter",
    element: null,
    planet: "jupiter",
    zodiac: null,
    confidence: "very-high",
    keywords: ["fate", "cycles", "turning point", "luck", "destiny"],
    jungianArchetype: "The Self",
    description: "The Wheel of Fortune represents the cyclical nature of life and the role of fate. It reminds us that change is constant, and fortune rises and falls according to cosmic patterns.",
    uprightMeanings: ["good luck", "karma", "life cycles", "destiny", "turning point"],
    reversedMeanings: ["bad luck", "resistance to change", "breaking cycles", "upheaval"],
    imagePath: "/images/archetypes/10-wheel-of-fortune.jpg",
  },

  justice: {
    slug: "justice",
    name: "Justice",
    number: 11,
    romanNumeral: "XI",
    hebrewLetter: {
      letter: "\u05DC",
      name: "Lamed",
      meaning: "Ox Goad",
      value: 30,
    },
    attributionType: "zodiac",
    primaryAttribution: "Libra",
    element: "air",
    planet: null,
    zodiac: "libra",
    confidence: "high",
    keywords: ["fairness", "truth", "cause and effect", "law", "balance"],
    jungianArchetype: "The Judge",
    description: "Justice holds the scales of balance and the sword of discernment. She represents the universal law of cause and effect, calling us to take responsibility for our actions.",
    uprightMeanings: ["justice", "fairness", "truth", "cause and effect", "law"],
    reversedMeanings: ["unfairness", "dishonesty", "lack of accountability", "corruption"],
    imagePath: "/images/archetypes/11-justice.jpg",
  },

  "the-hanged-man": {
    slug: "the-hanged-man",
    name: "The Hanged Man",
    number: 12,
    romanNumeral: "XII",
    hebrewLetter: {
      letter: "\u05DE",
      name: "Mem",
      meaning: "Water",
      value: 40,
    },
    attributionType: "element",
    primaryAttribution: "Water",
    element: "water",
    planet: null,
    zodiac: null,
    confidence: "moderate",
    keywords: ["surrender", "letting go", "sacrifice", "new perspective", "pause"],
    jungianArchetype: "The Martyr",
    description: "The Hanged Man hangs suspended between worlds, gaining wisdom through surrender. His peaceful expression reveals that letting go brings enlightenment and a completely new perspective.",
    uprightMeanings: ["pause", "surrender", "letting go", "new perspective", "sacrifice"],
    reversedMeanings: ["stalling", "resistance", "indecision", "avoiding sacrifice"],
    imagePath: "/images/archetypes/12-the-hanged-man.jpg",
  },

  death: {
    slug: "death",
    name: "Death",
    number: 13,
    romanNumeral: "XIII",
    hebrewLetter: {
      letter: "\u05E0",
      name: "Nun",
      meaning: "Fish",
      value: 50,
    },
    attributionType: "zodiac",
    primaryAttribution: "Scorpio",
    element: "water",
    planet: null,
    zodiac: "scorpio",
    confidence: "high",
    keywords: ["endings", "transformation", "transition", "release", "change"],
    jungianArchetype: "The Shadow",
    description: "Death represents profound transformation, the ending of one chapter so another can begin. The skeleton rides forth impartially, reminding us that change is inevitable and necessary for growth.",
    uprightMeanings: ["endings", "change", "transformation", "transition", "release"],
    reversedMeanings: ["resistance to change", "fear of change", "stagnation", "decay"],
    imagePath: "/images/archetypes/13-death.jpg",
  },

  temperance: {
    slug: "temperance",
    name: "Temperance",
    number: 14,
    romanNumeral: "XIV",
    hebrewLetter: {
      letter: "\u05E1",
      name: "Samekh",
      meaning: "Prop/Support",
      value: 60,
    },
    attributionType: "zodiac",
    primaryAttribution: "Sagittarius",
    element: "fire",
    planet: null,
    zodiac: "sagittarius",
    confidence: "high",
    keywords: ["balance", "moderation", "patience", "purpose", "alchemy"],
    jungianArchetype: "The Healer",
    description: "Temperance pours essence between cups in perfect balance, representing the alchemical blending of opposites. This angel teaches moderation, patience, and the middle path.",
    uprightMeanings: ["balance", "moderation", "patience", "purpose", "meaning"],
    reversedMeanings: ["imbalance", "excess", "self-healing", "re-alignment"],
    imagePath: "/images/archetypes/14-temperance.jpg",
  },

  "the-devil": {
    slug: "the-devil",
    name: "The Devil",
    number: 15,
    romanNumeral: "XV",
    hebrewLetter: {
      letter: "\u05E2",
      name: "Ayin",
      meaning: "Eye",
      value: 70,
    },
    attributionType: "zodiac",
    primaryAttribution: "Capricorn",
    element: "earth",
    planet: null,
    zodiac: "capricorn",
    confidence: "high",
    keywords: ["bondage", "materialism", "shadow self", "attachment", "addiction"],
    jungianArchetype: "The Shadow",
    description: "The Devil exposes our bondage to material desires and limiting beliefs. The chains are loose; we could escape if we chose. This card invites us to confront our shadow and reclaim our power.",
    uprightMeanings: ["shadow self", "attachment", "addiction", "restriction", "sexuality"],
    reversedMeanings: ["releasing limiting beliefs", "exploring dark thoughts", "detachment"],
    imagePath: "/images/archetypes/15-the-devil.jpg",
  },

  "the-tower": {
    slug: "the-tower",
    name: "The Tower",
    number: 16,
    romanNumeral: "XVI",
    hebrewLetter: {
      letter: "\u05E4",
      name: "Peh",
      meaning: "Mouth",
      value: 80,
    },
    attributionType: "planet",
    primaryAttribution: "Mars",
    element: null,
    planet: "mars",
    zodiac: null,
    confidence: "high",
    keywords: ["upheaval", "revelation", "sudden change", "awakening", "liberation"],
    jungianArchetype: "The Destroyer",
    description: "The Tower is struck by lightning, shattering false structures built on shaky foundations. Though sudden and disruptive, this destruction clears the way for authentic reconstruction.",
    uprightMeanings: ["sudden change", "upheaval", "chaos", "revelation", "awakening"],
    reversedMeanings: ["fear of change", "avoiding disaster", "delaying the inevitable"],
    imagePath: "/images/archetypes/16-the-tower.jpg",
  },

  "the-star": {
    slug: "the-star",
    name: "The Star",
    number: 17,
    romanNumeral: "XVII",
    hebrewLetter: {
      letter: "\u05E6",
      name: "Tzaddi",
      meaning: "Fish Hook",
      value: 90,
    },
    attributionType: "zodiac",
    primaryAttribution: "Aquarius",
    element: "air",
    planet: null,
    zodiac: "aquarius",
    confidence: "high",
    keywords: ["hope", "faith", "purpose", "renewal", "inspiration"],
    jungianArchetype: "The Muse",
    description: "The Star shines after the destruction of the Tower, offering hope and spiritual guidance. The nude figure pours water on land and sea, symbolizing the renewal of life and purpose.",
    uprightMeanings: ["hope", "faith", "purpose", "renewal", "spirituality"],
    reversedMeanings: ["lack of faith", "despair", "disconnection", "discouragement"],
    imagePath: "/images/archetypes/17-the-star.jpg",
  },

  "the-moon": {
    slug: "the-moon",
    name: "The Moon",
    number: 18,
    romanNumeral: "XVIII",
    hebrewLetter: {
      letter: "\u05E7",
      name: "Qoph",
      meaning: "Back of Head",
      value: 100,
    },
    attributionType: "zodiac",
    primaryAttribution: "Pisces",
    element: "water",
    planet: null,
    zodiac: "pisces",
    confidence: "high",
    keywords: ["illusion", "intuition", "fear", "subconscious", "dreams"],
    jungianArchetype: "The Anima",
    description: "The Moon illuminates the path through darkness but also casts shadows that deceive. This card represents the realm of dreams, fears, and the subconscious mind.",
    uprightMeanings: ["illusion", "fear", "anxiety", "subconscious", "intuition"],
    reversedMeanings: ["release of fear", "repressed emotion", "inner confusion"],
    imagePath: "/images/archetypes/18-the-moon.jpg",
  },

  "the-sun": {
    slug: "the-sun",
    name: "The Sun",
    number: 19,
    romanNumeral: "XIX",
    hebrewLetter: {
      letter: "\u05E8",
      name: "Resh",
      meaning: "Head",
      value: 200,
    },
    attributionType: "planet",
    primaryAttribution: "Sun",
    element: null,
    planet: "sun",
    zodiac: null,
    confidence: "very-high",
    keywords: ["joy", "success", "vitality", "positivity", "truth"],
    jungianArchetype: "The Divine Child",
    description: "The Sun radiates warmth, joy, and clarity after the mysteries of the Moon. The child rides forth in innocence, symbolizing the pure joy and vitality that comes with enlightenment.",
    uprightMeanings: ["positivity", "fun", "warmth", "success", "vitality"],
    reversedMeanings: ["inner child", "feeling down", "overly optimistic", "temporary depression"],
    imagePath: "/images/archetypes/19-the-sun.jpg",
  },

  judgement: {
    slug: "judgement",
    name: "Judgement",
    number: 20,
    romanNumeral: "XX",
    hebrewLetter: {
      letter: "\u05E9",
      name: "Shin",
      meaning: "Tooth",
      value: 300,
    },
    attributionType: "element",
    primaryAttribution: "Fire",
    element: "fire",
    planet: null,
    zodiac: null,
    confidence: "moderate",
    keywords: ["judgement", "rebirth", "inner calling", "absolution", "reflection"],
    jungianArchetype: "The Resurrection",
    description: "Judgement sounds the call to awakening and self-evaluation. The dead rise from their graves to answer this higher calling, representing spiritual rebirth and the culmination of a cycle.",
    uprightMeanings: ["judgement", "rebirth", "inner calling", "absolution", "reflection"],
    reversedMeanings: ["self-doubt", "ignoring the call", "refusal to change"],
    imagePath: "/images/archetypes/20-judgement.jpg",
  },

  "the-world": {
    slug: "the-world",
    name: "The World",
    number: 21,
    romanNumeral: "XXI",
    hebrewLetter: {
      letter: "\u05EA",
      name: "Tau",
      meaning: "Cross/Mark",
      value: 400,
    },
    attributionType: "planet",
    primaryAttribution: "Saturn",
    element: null,
    planet: "saturn",
    zodiac: null,
    confidence: "very-high",
    keywords: ["completion", "integration", "accomplishment", "wholeness", "travel"],
    jungianArchetype: "The Self",
    description: "The World represents the successful completion of the Fool's journey and the integration of all lessons learned. The dancing figure is surrounded by a wreath of achievement, symbolizing wholeness and fulfillment.",
    uprightMeanings: ["completion", "integration", "accomplishment", "travel", "achievement"],
    reversedMeanings: ["seeking personal closure", "short-cuts", "delays", "incomplete"],
    imagePath: "/images/archetypes/21-the-world.jpg",
  },
};

/**
 * Get all archetypes as an array (ordered by number)
 */
export function getAllArchetypes(): Archetype[] {
  return Object.values(ARCHETYPES).sort((a, b) => a.number - b.number);
}

/**
 * Get an archetype by slug
 */
export function getArchetypeBySlug(slug: string): Archetype | undefined {
  return ARCHETYPES[slug as ArchetypeSlug];
}

/**
 * Get an archetype by number (0-21)
 */
export function getArchetypeByNumber(number: number): Archetype | undefined {
  return getAllArchetypes().find((a) => a.number === number);
}
