/**
 * Pattern injection templates.
 *
 * Generated by scripts/generate-templates.ts
 */

import type { PatternInjection } from "../types";

const injections: PatternInjection[] = [
  // Injections will be populated by generation script
];

export default injections;
