"use client";

import { motion, type Variants } from "motion/react";
import { EASE_STANDARD } from "@/lib/animation-constants";
import { cn } from "@/lib/utils";

/**
 * PrivacyBand - Full-width dark section for privacy messaging
 *
 * Features:
 * - Warm charcoal background with grain overlay inheritance
 * - Gold border accents on top and bottom
 * - Centered content with max-width constraint
 * - Custom gold bullet points (diamond SVGs)
 * - Staggered entrance animations
 */

// Animation variants
const containerVariants: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.12,
      delayChildren: 0.2,
    },
  },
};

const headlineVariants: Variants = {
  hidden: {
    opacity: 0,
    y: 20,
  },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      ease: EASE_STANDARD,
    },
  },
};

const itemVariants: Variants = {
  hidden: {
    opacity: 0,
    x: -16,
  },
  visible: {
    opacity: 1,
    x: 0,
    transition: {
      duration: 0.5,
      ease: EASE_STANDARD,
    },
  },
};

// Gold diamond bullet SVG
function GoldBullet({ className }: { className?: string }) {
  return (
    <svg
      className={cn("h-3 w-3 flex-shrink-0 text-[var(--color-gold)]", className)}
      viewBox="0 0 12 12"
      fill="currentColor"
    >
      <path d="M6 0L12 6L6 12L0 6Z" />
    </svg>
  );
}

interface PrivacyPointProps {
  title: string;
  description: string;
}

function PrivacyPoint({ title, description }: PrivacyPointProps) {
  return (
    <motion.div
      className="flex gap-4"
      variants={itemVariants}
    >
      <GoldBullet className="mt-1.5" />
      <div>
        <p className="font-heading text-lg font-medium text-foreground">
          {title}
        </p>
        <p className="mt-1 text-muted-foreground">
          {description}
        </p>
      </div>
    </motion.div>
  );
}

export function PrivacyBand() {
  return (
    <section className="relative">
      {/* Top gold border */}
      <div
        className="absolute left-0 right-0 top-0 h-px"
        style={{
          background: "linear-gradient(to right, transparent, var(--color-gold), transparent)",
        }}
      />

      {/* Dark background band */}
      <div className="bg-[var(--color-warm-charcoal)] py-20 sm:py-24 lg:py-32">
        <motion.div
          className="container mx-auto max-w-3xl px-4 sm:px-6 lg:px-8"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={containerVariants}
        >
          {/* Headline */}
          <motion.h2
            className="font-display text-center text-3xl tracking-tight text-[var(--color-cream)] sm:text-4xl"
            variants={headlineVariants}
          >
            Your Practice Is Yours.
          </motion.h2>

          {/* Intro */}
          <motion.p
            className="mt-6 text-center text-lg text-[var(--color-warm-gray)]"
            variants={headlineVariants}
          >
            Spiritual practice is personal. Your data should be too.
          </motion.p>

          {/* Privacy points */}
          <div className="mt-12 space-y-8 sm:mt-16">
            <PrivacyPoint
              title="We don't monetize your inner life."
              description="Your sightings, interpretations, and patterns aren't analyzed for advertising, sold to third parties, or used to build profiles."
            />

            <PrivacyPoint
              title="You own your data."
              description="Export everything you've captured, anytime. Delete your account and your data goes with it. No retention tricks."
            />

            <PrivacyPoint
              title="We're transparent about what we use."
              description="Signal interpretations are generated by Claude (Anthropic's AI). Your data is processed to create the interpretation, then forgotten."
            />

            <PrivacyPoint
              title="Privacy isn't a feature we added."
              description="It's how we built from the start. What you notice stays between you and the patterns."
            />
          </div>
        </motion.div>
      </div>

      {/* Bottom gold border */}
      <div
        className="absolute bottom-0 left-0 right-0 h-px"
        style={{
          background: "linear-gradient(to right, transparent, var(--color-gold), transparent)",
        }}
      />
    </section>
  );
}

export default PrivacyBand;
