import "@radix-ui/themes/styles.css";
import "@/styles/globals.css";

import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import {
  Cinzel_Decorative,
  Cormorant_Garamond,
  Crimson_Pro,
} from "next/font/google";
import { type Metadata } from "next";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { MotionProvider } from "@/components/motion-provider";
import { SkipToContent } from "@/components/skip-to-content";
import {
  StructuredData,
  createWebSiteSchema,
} from "@/components/structured-data";
import { AuthProvider } from "@/components/auth/auth-provider";
import { AuthModal } from "@/components/auth/auth-modal";
import { EmailVerificationBanner } from "@/components/auth/email-verification-banner";
import { CartProvider } from "@/lib/shop/cart-context";
import { isAuthEnabled } from "@/lib/features/access";
import { ThemeProvider } from "@/lib/theme";
import { ThemeWrapper } from "@/components/theme-wrapper";
import { QueryProvider } from "@/components/query-provider";

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://wavepoint.space";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "WavePoint - Explore Sacred Geometry and Divine Patterns",
    template: "%s | WavePoint",
  },
  description:
    "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "WavePoint",
    // OG image is dynamically generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
  },
};

// Display font for hero titles and page headings
const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-display",
  display: "swap",
});

// Heading font for section headings and card titles
const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-heading",
  display: "swap",
});

// Body font for text and descriptions
const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-body",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Check if public auth UI should be shown (env flags)
  // AuthProvider is always included so useSession() works for admin access checks
  const authUiEnabled = isAuthEnabled();

  // Core content - always wrapped with AuthProvider for session access
  const coreContent = (
    <MotionProvider>
      <Header />
      {authUiEnabled && <EmailVerificationBanner />}
      <main id="main-content">{children}</main>
      <Footer />
    </MotionProvider>
  );

  return (
    <html
      lang="en"
      className={`${cinzelDecorative.variable} ${cormorantGaramond.variable} ${crimsonPro.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Flash-prevention script - runs before React hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('wavepoint-theme');
                  var isDark = theme === 'dark' ||
                    (theme !== 'light' && window.matchMedia('(prefers-color-scheme: dark)').matches);
                  if (isDark) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body>
        <StructuredData
          data={createWebSiteSchema(
            BASE_URL,
            "WavePoint",
            "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms."
          )}
        />
        <SkipToContent />
        <ThemeProvider>
          <ThemeWrapper>
            {/* AuthProvider always included for session access (admin checks, etc.) */}
            <AuthProvider>
              {/* AuthModal always rendered - it only displays when isOpen is true.
                  This allows invite flows to work even when auth is disabled for public.
                  The modal opens via URL params (?auth=sign-up&invite=...) */}
              <AuthModal />
              {/* QueryProvider for React Query hooks used across the app */}
              <QueryProvider>
                {/* CartProvider always included so useCart() works after session changes.
                    Components use useCanAccessShop() client-side for visibility control. */}
                <CartProvider>{coreContent}</CartProvider>
              </QueryProvider>
            </AuthProvider>
          </ThemeWrapper>
        </ThemeProvider>
      </body>
      <Analytics />
      <SpeedInsights />
    </html>
  );
}
