import "@radix-ui/themes/styles.css";
import "@/styles/globals.css";

import { Analytics } from "@vercel/analytics/next";
import {
  Cinzel_Decorative,
  Cormorant_Garamond,
  Crimson_Pro,
} from "next/font/google";
import { type Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { MotionProvider } from "@/components/motion-provider";
import { SkipToContent } from "@/components/skip-to-content";
import {
  StructuredData,
  createWebSiteSchema,
} from "@/components/structured-data";
import { AuthProvider } from "@/components/auth/auth-provider";
import { AuthModal } from "@/components/auth/auth-modal";
import { EmailVerificationBanner } from "@/components/auth/email-verification-banner";
import { CartProvider } from "@/lib/shop/cart-context";
import { auth } from "@/lib/auth";
import { isAuthEnabled, canAccessShop } from "@/lib/features/access";

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://wavepoint.space";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "WavePoint - Explore Sacred Geometry and Divine Patterns",
    template: "%s | WavePoint",
  },
  description:
    "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "WavePoint",
    // OG image is dynamically generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
  },
};

// Display font for hero titles and page headings
const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-display",
  display: "swap",
});

// Heading font for section headings and card titles
const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-heading",
  display: "swap",
});

// Body font for text and descriptions
const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-body",
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Get session for access checks
  const session = await auth();

  // Check if public auth UI should be shown (env flags)
  // AuthProvider is always included so useSession() works for admin access checks
  const authUiEnabled = isAuthEnabled();
  const shopAccessible = canAccessShop(session);

  // Core content - always wrapped with AuthProvider for session access
  const coreContent = (
    <MotionProvider>
      <Header />
      {authUiEnabled && <EmailVerificationBanner />}
      <main id="main-content">{children}</main>
      <Footer />
    </MotionProvider>
  );

  return (
    <html
      lang="en"
      className={`${cinzelDecorative.variable} ${cormorantGaramond.variable} ${crimsonPro.variable}`}
    >
      <body>
        <StructuredData
          data={createWebSiteSchema(
            BASE_URL,
            "WavePoint",
            "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms."
          )}
        />
        <SkipToContent />
        <Theme appearance="dark">
          {/* AuthProvider always included for session access (admin checks, etc.) */}
          <AuthProvider>
            {/* Auth UI (modal) only shown when auth feature is enabled for public */}
            {authUiEnabled && <AuthModal />}
            {/* CartProvider only when shop is accessible (flag or admin) */}
            {shopAccessible ? (
              <CartProvider>{coreContent}</CartProvider>
            ) : (
              coreContent
            )}
          </AuthProvider>
        </Theme>
      </body>
      <Analytics />
    </html>
  );
}
