/**
 * Activity modifiers.
 *
 * Generated by scripts/generate-templates.ts
 */

import type { ActivityModifier } from "../../types";

const modifiers: ActivityModifier[] = [
  // Modifiers will be populated by generation script
];

export default modifiers;
