/**
 * Element modifiers.
 *
 * Generated by scripts/generate-templates.ts
 */

import type { ElementModifier } from "../../types";

const modifiers: ElementModifier[] = [
  // Modifiers will be populated by generation script
];

export default modifiers;
