/**
 * Mood modifiers.
 *
 * Generated by scripts/generate-templates.ts
 */

import type { MoodModifier } from "../../types";

const modifiers: MoodModifier[] = [
  // Modifiers will be populated by generation script
];

export default modifiers;
