/**
 * Moon phase modifiers.
 *
 * Generated by scripts/generate-templates.ts
 */

import type { MoonModifier } from "../../types";

const modifiers: MoonModifier[] = [
  // Modifiers will be populated by generation script
];

export default modifiers;
