/**
 * Eclipse Data 2020-2030
 *
 * Static eclipse data sourced from NASA eclipse decade tables with
 * rich astrological interpretations added. This data is small enough
 * (~28KB uncompressed) to ship in the client bundle.
 *
 * NASA Sources:
 * - Solar: https://eclipse.gsfc.nasa.gov/SEdecade/SEdecade2021.html
 * - Lunar: https://eclipse.gsfc.nasa.gov/LEdecade/LEdecade2021.html
 */

import type { Eclipse, EclipsePortal } from "./types";

/**
 * All eclipses from 2020-2030.
 *
 * Sorted chronologically by date.
 */
export const ECLIPSES: Eclipse[] = [
  // ============================================================================
  // 2020
  // ============================================================================
  {
    id: "2020-01-10",
    date: "2020-01-10",
    timeUtc: "19:21",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "cancer",
    degree: 20,
    saros: 144,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Cancer",
    essence: "Emotional Roots",
    interpretation:
      "This Cancer lunar eclipse illuminates themes of home, family, and emotional security. The penumbral nature suggests subtle shifts in how we nurture ourselves and others. Old patterns of caretaking may dissolve as new approaches to emotional safety emerge.",
    themes: ["home", "family", "nurturing", "emotional security", "ancestry"],
    portalId: "2020-winter",
    portalPosition: "opener",
  },
  {
    id: "2020-06-05",
    date: "2020-06-05",
    timeUtc: "19:12",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "sagittarius",
    degree: 15,
    saros: 111,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Sagittarius",
    essence: "Truth Unveiled",
    interpretation:
      "A Sagittarian eclipse that questions our beliefs and expands our worldview. Penumbral eclipses work subtly, gradually revealing where our philosophies may have become limiting. Travel, education, and spiritual seeking are highlighted.",
    themes: ["beliefs", "truth", "expansion", "philosophy", "adventure"],
    portalId: "2020-summer",
    portalPosition: "opener",
  },
  {
    id: "2020-06-21",
    date: "2020-06-21",
    timeUtc: "06:41",
    type: "annular_solar",
    category: "solar",
    sign: "cancer",
    degree: 0,
    saros: 137,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Cancer",
    essence: "New Beginnings",
    interpretation:
      "On the Summer Solstice, this Cancer solar eclipse marks a powerful new beginning in matters of home, family, and emotional foundation. At 0° Cancer, this is a cardinal point eclipse with far-reaching effects on how we define belonging and safety.",
    themes: ["new beginnings", "home", "solstice", "cardinal point", "family"],
    portalId: "2020-summer",
    portalPosition: "closer",
  },
  {
    id: "2020-07-05",
    date: "2020-07-05",
    timeUtc: "04:30",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "capricorn",
    degree: 13,
    saros: 149,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Capricorn",
    essence: "Structure Released",
    interpretation:
      "This Capricorn eclipse challenges outdated structures and authority patterns. The penumbral quality softens the release, allowing gradual dissolution of what no longer serves our ambitions and public roles.",
    themes: ["authority", "structure", "ambition", "responsibility", "legacy"],
    portalId: null,
    portalPosition: null,
  },
  {
    id: "2020-11-30",
    date: "2020-11-30",
    timeUtc: "09:30",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "gemini",
    degree: 8,
    saros: 116,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Gemini",
    essence: "Mind Shift",
    interpretation:
      "A Gemini eclipse that transforms how we communicate and process information. Old mental patterns and outdated ways of thinking are gently released, making room for fresh perspectives and new connections.",
    themes: ["communication", "learning", "curiosity", "duality", "connections"],
    portalId: "2020-fall",
    portalPosition: "opener",
  },
  {
    id: "2020-12-14",
    date: "2020-12-14",
    timeUtc: "16:14",
    type: "total_solar",
    category: "solar",
    sign: "sagittarius",
    degree: 23,
    saros: 142,
    isPenumbral: false,
    title: "Total Solar Eclipse in Sagittarius",
    essence: "Vision Quest",
    interpretation:
      "A powerful total solar eclipse initiating a new chapter in our quest for meaning, truth, and expansion. This eclipse asks us to plant seeds of faith and commit to a larger vision. What beliefs will guide your next journey?",
    themes: ["vision", "faith", "expansion", "truth-seeking", "adventure"],
    portalId: "2020-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2021
  // ============================================================================
  {
    id: "2021-05-26",
    date: "2021-05-26",
    timeUtc: "11:14",
    type: "total_lunar",
    category: "lunar",
    sign: "sagittarius",
    degree: 5,
    saros: 121,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Sagittarius",
    essence: "Truth Illuminated",
    interpretation:
      "This total lunar eclipse in Sagittarius brings powerful revelations about our beliefs and life philosophy. Known as a 'Blood Moon,' it illuminates what we must release to continue our expansion. Old truths fall away to make room for new understanding.",
    themes: ["revelation", "truth", "release", "philosophy", "expansion"],
    portalId: "2021-spring",
    portalPosition: "opener",
  },
  {
    id: "2021-06-10",
    date: "2021-06-10",
    timeUtc: "10:43",
    type: "annular_solar",
    category: "solar",
    sign: "gemini",
    degree: 19,
    saros: 147,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Gemini",
    essence: "New Voice",
    interpretation:
      "This Gemini solar eclipse opens a new chapter in how we communicate, learn, and connect. The 'ring of fire' eclipse invites us to embrace new ideas and ways of sharing information. A portal for writing, speaking, and intellectual pursuits.",
    themes: ["communication", "learning", "new ideas", "connections", "voice"],
    portalId: "2021-spring",
    portalPosition: "closer",
  },
  {
    id: "2021-11-19",
    date: "2021-11-19",
    timeUtc: "09:04",
    type: "partial_lunar",
    category: "lunar",
    sign: "taurus",
    degree: 27,
    saros: 126,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Taurus",
    essence: "Values Revealed",
    interpretation:
      "The longest partial lunar eclipse in centuries illuminates Taurus themes of values, resources, and self-worth. What we once thought stable may be revealed as shifting ground. An invitation to release attachment to material security.",
    themes: ["values", "resources", "self-worth", "stability", "release"],
    portalId: "2021-fall",
    portalPosition: "opener",
  },
  {
    id: "2021-12-04",
    date: "2021-12-04",
    timeUtc: "07:34",
    type: "total_solar",
    category: "solar",
    sign: "sagittarius",
    degree: 12,
    saros: 152,
    isPenumbral: false,
    title: "Total Solar Eclipse in Sagittarius",
    essence: "Faith Renewed",
    interpretation:
      "A total solar eclipse in Sagittarius initiates new journeys of faith, learning, and exploration. Visible primarily over Antarctica, this eclipse plants seeds for adventures yet to come. What new philosophy or spiritual path is calling?",
    themes: ["faith", "adventure", "learning", "exploration", "meaning"],
    portalId: "2021-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2022
  // ============================================================================
  {
    id: "2022-04-30",
    date: "2022-04-30",
    timeUtc: "20:28",
    type: "partial_solar",
    category: "solar",
    sign: "taurus",
    degree: 10,
    saros: 119,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Taurus",
    essence: "New Ground",
    interpretation:
      "This Taurus solar eclipse initiates a new cycle around values, resources, and what we truly need to feel secure. With both luminaries in the sign of the Bull, we're invited to plant seeds for lasting material and spiritual foundations.",
    themes: ["values", "security", "foundation", "resources", "stability"],
    portalId: "2022-spring",
    portalPosition: "opener",
  },
  {
    id: "2022-05-16",
    date: "2022-05-16",
    timeUtc: "04:12",
    type: "total_lunar",
    category: "lunar",
    sign: "scorpio",
    degree: 25,
    saros: 131,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Scorpio",
    essence: "Deep Release",
    interpretation:
      "A powerful Blood Moon in Scorpio brings intense revelations about power, intimacy, and shared resources. This eclipse illuminates what we've been holding onto—debts, resentments, or transformations we've been avoiding. Time to let go.",
    themes: ["transformation", "release", "power", "intimacy", "rebirth"],
    portalId: "2022-spring",
    portalPosition: "closer",
  },
  {
    id: "2022-10-25",
    date: "2022-10-25",
    timeUtc: "11:01",
    type: "partial_solar",
    category: "solar",
    sign: "scorpio",
    degree: 2,
    saros: 124,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Scorpio",
    essence: "Power Reset",
    interpretation:
      "This Scorpio solar eclipse begins a new chapter in our relationship with power, transformation, and the mysteries of life and death. At 2° Scorpio, fresh starts in shared resources, psychological depth, and intimate bonds are highlighted.",
    themes: ["power", "transformation", "intimacy", "mystery", "rebirth"],
    portalId: "2022-fall",
    portalPosition: "opener",
  },
  {
    id: "2022-11-08",
    date: "2022-11-08",
    timeUtc: "10:59",
    type: "total_lunar",
    category: "lunar",
    sign: "taurus",
    degree: 16,
    saros: 136,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Taurus",
    essence: "Values Transformed",
    interpretation:
      "The final eclipse on the Taurus-Scorpio axis brings culmination to themes of values versus desires, stability versus transformation. This Blood Moon reveals what we've built and what must now change. A powerful portal for releasing attachments.",
    themes: ["culmination", "values", "release", "transformation", "attachment"],
    portalId: "2022-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2023
  // ============================================================================
  {
    id: "2023-04-20",
    date: "2023-04-20",
    timeUtc: "04:13",
    type: "hybrid_solar",
    category: "solar",
    sign: "aries",
    degree: 29,
    saros: 129,
    isPenumbral: false,
    title: "Hybrid Solar Eclipse in Aries",
    essence: "Identity Spark",
    interpretation:
      "A rare hybrid eclipse (both total and annular) at the critical 29th degree of Aries. This powerful initiation point ignites new beginnings around identity, courage, and self-assertion. The final degree of Aries demands we complete one chapter of self-discovery before beginning another.",
    themes: ["identity", "courage", "initiation", "self-assertion", "completion"],
    portalId: "2023-spring",
    portalPosition: "opener",
  },
  {
    id: "2023-05-05",
    date: "2023-05-05",
    timeUtc: "17:24",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "scorpio",
    degree: 14,
    saros: 141,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Scorpio",
    essence: "Subtle Depths",
    interpretation:
      "A gentle penumbral eclipse in Scorpio allows for subtle processing of deep emotions and power dynamics. This softer lunar eclipse helps release psychological patterns without the intensity of a total eclipse. Quiet transformation unfolds.",
    themes: ["psychology", "subtle release", "power", "depth", "processing"],
    portalId: "2023-spring",
    portalPosition: "closer",
  },
  {
    id: "2023-10-14",
    date: "2023-10-14",
    timeUtc: "18:00",
    type: "annular_solar",
    category: "solar",
    sign: "libra",
    degree: 21,
    saros: 134,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Libra",
    essence: "Partnership Portal",
    interpretation:
      "The 'Ring of Fire' eclipse in Libra opens a new chapter in relationships, partnerships, and balance. This eclipse activates the Aries-Libra axis that will be prominent through 2024-2025, initiating fresh starts in how we relate to others.",
    themes: ["relationships", "balance", "partnership", "harmony", "justice"],
    portalId: "2023-fall",
    portalPosition: "opener",
  },
  {
    id: "2023-10-28",
    date: "2023-10-28",
    timeUtc: "20:14",
    type: "partial_lunar",
    category: "lunar",
    sign: "taurus",
    degree: 5,
    saros: 146,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Taurus",
    essence: "Grounded Release",
    interpretation:
      "This Taurus lunar eclipse helps release outdated attachments to comfort zones and material security. As the Moon is partially shadowed, we're invited to let go of what we've been holding too tightly while honoring what truly sustains us.",
    themes: ["comfort", "security", "release", "grounding", "values"],
    portalId: "2023-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2024
  // ============================================================================
  {
    id: "2024-03-25",
    date: "2024-03-25",
    timeUtc: "07:13",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "libra",
    degree: 5,
    saros: 113,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Libra",
    essence: "Relationship Shift",
    interpretation:
      "A subtle penumbral eclipse in Libra gently illuminates relationship dynamics and patterns of people-pleasing. This eclipse begins the 2024 eclipse season, preparing us for the powerful solar eclipse to follow. Relationship karma is subtly activated.",
    themes: ["relationships", "balance", "karma", "partnership", "harmony"],
    portalId: "2024-spring",
    portalPosition: "opener",
  },
  {
    id: "2024-04-08",
    date: "2024-04-08",
    timeUtc: "18:18",
    type: "total_solar",
    category: "solar",
    sign: "aries",
    degree: 19,
    saros: 139,
    isPenumbral: false,
    title: "Total Solar Eclipse in Aries",
    essence: "Bold Beginning",
    interpretation:
      "The 'Great North American Eclipse' brings a powerful new beginning in Aries, the sign of the self. Visible across Mexico, the US, and Canada, this total solar eclipse initiates a bold new chapter of self-discovery, courage, and independent action. A rare opportunity to plant seeds for who you're becoming.",
    themes: ["new beginning", "courage", "identity", "independence", "action"],
    portalId: "2024-spring",
    portalPosition: "closer",
  },
  {
    id: "2024-09-18",
    date: "2024-09-18",
    timeUtc: "02:44",
    type: "partial_lunar",
    category: "lunar",
    sign: "pisces",
    degree: 25,
    saros: 118,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Pisces",
    essence: "Dream Release",
    interpretation:
      "This Pisces lunar eclipse illuminates our dreams, illusions, and spiritual connections. As the Moon passes through Earth's shadow, we're invited to release fantasies that no longer serve us and honor the mystical dimensions of life that do.",
    themes: ["dreams", "spirituality", "illusion", "release", "compassion"],
    portalId: "2024-fall",
    portalPosition: "opener",
  },
  {
    id: "2024-10-02",
    date: "2024-10-02",
    timeUtc: "18:49",
    type: "annular_solar",
    category: "solar",
    sign: "libra",
    degree: 10,
    saros: 144,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Libra",
    essence: "Justice Rising",
    interpretation:
      "The second 'Ring of Fire' eclipse in Libra within a year continues the powerful activation of relationship themes. This eclipse asks us to find new balance, seek justice, and initiate fresh approaches to partnership. What new social contracts are you ready to create?",
    themes: ["justice", "balance", "partnership", "fairness", "new agreements"],
    portalId: "2024-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2025
  // ============================================================================
  {
    id: "2025-03-14",
    date: "2025-03-14",
    timeUtc: "06:55",
    type: "total_lunar",
    category: "lunar",
    sign: "virgo",
    degree: 24,
    saros: 123,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Virgo",
    essence: "Service Transformed",
    interpretation:
      "A total Blood Moon in Virgo illuminates themes of service, health, and daily routines. This eclipse reveals what needs to change in how we care for ourselves and serve others. Perfectionism may be released as we embrace a more holistic approach to well-being.",
    themes: ["service", "health", "routines", "perfectionism", "healing"],
    portalId: "2025-spring",
    portalPosition: "opener",
  },
  {
    id: "2025-03-29",
    date: "2025-03-29",
    timeUtc: "10:48",
    type: "partial_solar",
    category: "solar",
    sign: "aries",
    degree: 9,
    saros: 149,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Aries",
    essence: "Self Renewed",
    interpretation:
      "This Aries solar eclipse continues the theme of identity transformation begun in 2024. A partial eclipse plants seeds for new expressions of courage and self-assertion. The Aries-Libra eclipse cycle approaches its conclusion, refining our sense of self in relationship.",
    themes: ["identity", "courage", "renewal", "self-expression", "initiation"],
    portalId: "2025-spring",
    portalPosition: "closer",
  },
  {
    id: "2025-09-07",
    date: "2025-09-07",
    timeUtc: "18:12",
    type: "total_lunar",
    category: "lunar",
    sign: "pisces",
    degree: 15,
    saros: 128,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Pisces",
    essence: "Mystic Completion",
    interpretation:
      "A powerful Blood Moon in Pisces brings culmination to spiritual themes and creative dreams. This eclipse illuminates the mystical dimensions of life, inviting release of illusions while honoring genuine spiritual insights. Compassion and transcendence are highlighted.",
    themes: ["spirituality", "dreams", "completion", "compassion", "transcendence"],
    portalId: "2025-fall",
    portalPosition: "opener",
  },
  {
    id: "2025-09-21",
    date: "2025-09-21",
    timeUtc: "19:43",
    type: "partial_solar",
    category: "solar",
    sign: "virgo",
    degree: 29,
    saros: 154,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Virgo",
    essence: "Sacred Service",
    interpretation:
      "At the critical 29th degree of Virgo, this solar eclipse marks the completion of one cycle of service and the beginning of another. New approaches to health, daily routines, and practical spirituality are initiated. The final degree demands mastery before moving on.",
    themes: ["service", "completion", "health", "mastery", "practical wisdom"],
    portalId: "2025-fall",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2026
  // ============================================================================
  {
    id: "2026-02-17",
    date: "2026-02-17",
    timeUtc: "12:01",
    type: "annular_solar",
    category: "solar",
    sign: "aquarius",
    degree: 29,
    saros: 121,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Aquarius",
    essence: "Vision Activated",
    interpretation:
      "A 'Ring of Fire' eclipse at the final degree of Aquarius initiates new visions for collective progress and humanitarian ideals. This eclipse asks us to complete one chapter of social innovation before beginning another. What future are you ready to create?",
    themes: ["innovation", "collective", "future", "humanitarianism", "vision"],
    portalId: "2026-winter",
    portalPosition: "opener",
  },
  {
    id: "2026-03-03",
    date: "2026-03-03",
    timeUtc: "11:34",
    type: "total_lunar",
    category: "lunar",
    sign: "virgo",
    degree: 12,
    saros: 133,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Virgo",
    essence: "Healing Revealed",
    interpretation:
      "This Blood Moon in Virgo illuminates where our service and health practices need transformation. The total lunar eclipse reveals patterns of over-work or neglected self-care, inviting release of what no longer serves our well-being.",
    themes: ["healing", "service", "release", "health", "transformation"],
    portalId: "2026-winter",
    portalPosition: "closer",
  },
  {
    id: "2026-08-12",
    date: "2026-08-12",
    timeUtc: "17:47",
    type: "total_solar",
    category: "solar",
    sign: "leo",
    degree: 20,
    saros: 126,
    isPenumbral: false,
    title: "Total Solar Eclipse in Leo",
    essence: "Heart Ignited",
    interpretation:
      "A magnificent total solar eclipse in Leo activates themes of creativity, leadership, and heart-centered expression. Visible across Greenland, Iceland, and Spain, this eclipse initiates a powerful new cycle of self-expression and creative courage.",
    themes: ["creativity", "leadership", "heart", "self-expression", "courage"],
    portalId: "2026-summer",
    portalPosition: "opener",
  },
  {
    id: "2026-08-28",
    date: "2026-08-28",
    timeUtc: "04:13",
    type: "partial_lunar",
    category: "lunar",
    sign: "pisces",
    degree: 4,
    saros: 138,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Pisces",
    essence: "Dreams Released",
    interpretation:
      "This Pisces lunar eclipse gently illuminates our dreams and spiritual aspirations. As the Moon passes partially through Earth's shadow, we're invited to release illusions while honoring genuine intuitive wisdom and creative vision.",
    themes: ["dreams", "intuition", "release", "spirituality", "creativity"],
    portalId: "2026-summer",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2027
  // ============================================================================
  {
    id: "2027-02-06",
    date: "2027-02-06",
    timeUtc: "16:00",
    type: "annular_solar",
    category: "solar",
    sign: "aquarius",
    degree: 18,
    saros: 131,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Aquarius",
    essence: "Collective Vision",
    interpretation:
      "This Aquarian 'Ring of Fire' eclipse continues the activation of humanitarian and innovative themes. New visions for community, technology, and social progress are seeded. What revolutionary ideas are ready to be born?",
    themes: ["innovation", "community", "revolution", "technology", "progress"],
    portalId: "2027-winter",
    portalPosition: "opener",
  },
  {
    id: "2027-02-20",
    date: "2027-02-20",
    timeUtc: "23:13",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "virgo",
    degree: 2,
    saros: 143,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Virgo",
    essence: "Quiet Healing",
    interpretation:
      "A subtle penumbral eclipse in Virgo allows for gentle processing of health and service themes. This softer eclipse invites quiet reflection on daily routines and how we can better care for ourselves and others.",
    themes: ["healing", "reflection", "service", "routines", "self-care"],
    portalId: "2027-winter",
    portalPosition: "closer",
  },
  {
    id: "2027-07-18",
    date: "2027-07-18",
    timeUtc: "16:04",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "capricorn",
    degree: 25,
    saros: 148,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Capricorn",
    essence: "Authority Shift",
    interpretation:
      "This penumbral eclipse in Capricorn subtly illuminates structures, authority, and ambition. Old career goals or relationship to institutions may be quietly released as new approaches to success and responsibility emerge.",
    themes: ["authority", "structure", "ambition", "career", "responsibility"],
    portalId: "2027-summer",
    portalPosition: "opener",
  },
  {
    id: "2027-08-02",
    date: "2027-08-02",
    timeUtc: "10:07",
    type: "total_solar",
    category: "solar",
    sign: "leo",
    degree: 10,
    saros: 136,
    isPenumbral: false,
    title: "Total Solar Eclipse in Leo",
    essence: "Radiant Beginning",
    interpretation:
      "A spectacular total solar eclipse in Leo visible across North Africa, the Middle East, and India. This powerful eclipse initiates new creative ventures, leadership roles, and expressions of authentic self. The heart awakens to new possibilities.",
    themes: ["creativity", "leadership", "authenticity", "self-expression", "joy"],
    portalId: "2027-summer",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2028
  // ============================================================================
  {
    id: "2028-01-12",
    date: "2028-01-12",
    timeUtc: "04:07",
    type: "partial_lunar",
    category: "lunar",
    sign: "cancer",
    degree: 22,
    saros: 153,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Cancer",
    essence: "Home Illuminated",
    interpretation:
      "This Cancer lunar eclipse illuminates themes of home, family, and emotional security. Patterns of nurturing and dependency are revealed, inviting release of what no longer provides true safety. The Moon in her home sign asks: what does belonging really mean?",
    themes: ["home", "family", "security", "nurturing", "belonging"],
    portalId: "2028-winter",
    portalPosition: "opener",
  },
  {
    id: "2028-01-26",
    date: "2028-01-26",
    timeUtc: "15:08",
    type: "annular_solar",
    category: "solar",
    sign: "aquarius",
    degree: 6,
    saros: 141,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Aquarius",
    essence: "Future Seeded",
    interpretation:
      "This Aquarian eclipse plants seeds for collective evolution and technological advancement. The 'Ring of Fire' visible across South America initiates fresh approaches to community, friendship, and humanitarian goals.",
    themes: ["future", "community", "technology", "friendship", "innovation"],
    portalId: "2028-winter",
    portalPosition: "closer",
  },
  {
    id: "2028-07-06",
    date: "2028-07-06",
    timeUtc: "18:20",
    type: "partial_lunar",
    category: "lunar",
    sign: "capricorn",
    degree: 15,
    saros: 158,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Capricorn",
    essence: "Structure Revealed",
    interpretation:
      "This Capricorn eclipse illuminates our relationship with authority, career, and worldly ambition. What structures have we built? Which ones serve us and which confine us? The Moon's shadow invites honest assessment.",
    themes: ["career", "authority", "structure", "ambition", "assessment"],
    portalId: "2028-summer",
    portalPosition: "opener",
  },
  {
    id: "2028-07-22",
    date: "2028-07-22",
    timeUtc: "02:56",
    type: "total_solar",
    category: "solar",
    sign: "cancer",
    degree: 29,
    saros: 146,
    isPenumbral: false,
    title: "Total Solar Eclipse in Cancer",
    essence: "Root Renewal",
    interpretation:
      "At the anaretic 29th degree of Cancer, this powerful total solar eclipse marks the completion and renewal of home and family themes. Visible across Australia and New Zealand, this eclipse initiates deep transformation in how we nurture and are nurtured.",
    themes: ["home", "family", "completion", "nurturing", "renewal"],
    portalId: "2028-summer",
    portalPosition: "closer",
  },
  {
    id: "2028-12-31",
    date: "2028-12-31",
    timeUtc: "16:53",
    type: "total_lunar",
    category: "lunar",
    sign: "cancer",
    degree: 10,
    saros: 125,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Cancer",
    essence: "Year's Release",
    interpretation:
      "A fitting end to the year: a total Blood Moon in Cancer on New Year's Eve. This powerful eclipse illuminates emotional patterns and family dynamics, inviting release of the old as we prepare to welcome the new. A cosmic clearing for the year ahead.",
    themes: ["release", "family", "emotion", "clearing", "renewal"],
    portalId: null,
    portalPosition: null,
  },

  // ============================================================================
  // 2029
  // ============================================================================
  {
    id: "2029-01-14",
    date: "2029-01-14",
    timeUtc: "17:13",
    type: "partial_solar",
    category: "solar",
    sign: "capricorn",
    degree: 25,
    saros: 151,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Capricorn",
    essence: "Authority Renewed",
    interpretation:
      "This Capricorn solar eclipse initiates new approaches to career, authority, and long-term goals. Following the Cancer Blood Moon, this eclipse helps establish new structures and ambitions for the year ahead.",
    themes: ["career", "authority", "goals", "structure", "initiation"],
    portalId: "2029-winter",
    portalPosition: "opener",
  },
  {
    id: "2029-06-12",
    date: "2029-06-12",
    timeUtc: "04:06",
    type: "partial_solar",
    category: "solar",
    sign: "gemini",
    degree: 21,
    saros: 156,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Gemini",
    essence: "Mind Awakened",
    interpretation:
      "This Gemini solar eclipse plants seeds for new ways of thinking, communicating, and learning. Fresh intellectual pursuits and connections are initiated. What new ideas are ready to be explored?",
    themes: ["communication", "learning", "ideas", "connections", "curiosity"],
    portalId: "2029-summer",
    portalPosition: "opener",
  },
  {
    id: "2029-06-26",
    date: "2029-06-26",
    timeUtc: "03:22",
    type: "total_lunar",
    category: "lunar",
    sign: "capricorn",
    degree: 4,
    saros: 130,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Capricorn",
    essence: "Legacy Transformed",
    interpretation:
      "A total Blood Moon in Capricorn illuminates our relationship with achievement, authority, and legacy. What we've built in the world is revealed in full light. Time to release attachments to status and embrace authentic ambition.",
    themes: ["legacy", "achievement", "authority", "release", "authenticity"],
    portalId: "2029-summer",
    portalPosition: "closer",
  },
  {
    id: "2029-07-11",
    date: "2029-07-11",
    timeUtc: "15:37",
    type: "partial_lunar",
    category: "lunar",
    sign: "capricorn",
    degree: 19,
    saros: 168,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Capricorn",
    essence: "Structure Adjusted",
    interpretation:
      "A rare third eclipse in summer 2029, this partial lunar eclipse continues the Capricorn theme of authority and structure. Additional adjustment to career and worldly goals may be needed. The universe asks for refinement.",
    themes: ["adjustment", "structure", "career", "refinement", "authority"],
    portalId: null,
    portalPosition: null,
  },
  {
    id: "2029-12-05",
    date: "2029-12-05",
    timeUtc: "15:52",
    type: "partial_solar",
    category: "solar",
    sign: "sagittarius",
    degree: 14,
    saros: 161,
    isPenumbral: false,
    title: "Partial Solar Eclipse in Sagittarius",
    essence: "Faith Renewed",
    interpretation:
      "This Sagittarian solar eclipse plants seeds for new adventures, beliefs, and expansive visions. A perfect end to the decade of transformation, inviting us to look forward with optimism and philosophical wisdom.",
    themes: ["faith", "adventure", "expansion", "wisdom", "optimism"],
    portalId: "2029-winter-2",
    portalPosition: "opener",
  },
  {
    id: "2029-12-20",
    date: "2029-12-20",
    timeUtc: "22:43",
    type: "total_lunar",
    category: "lunar",
    sign: "gemini",
    degree: 29,
    saros: 135,
    isPenumbral: false,
    title: "Total Lunar Eclipse in Gemini",
    essence: "Truth Completed",
    interpretation:
      "At the final degree of Gemini, this Blood Moon marks the completion of a cycle of learning and communication. Old ways of thinking are fully illuminated and released. The mind is cleared for new understanding as the year ends.",
    themes: ["completion", "truth", "communication", "release", "understanding"],
    portalId: "2029-winter-2",
    portalPosition: "closer",
  },

  // ============================================================================
  // 2030
  // ============================================================================
  {
    id: "2030-06-01",
    date: "2030-06-01",
    timeUtc: "06:29",
    type: "annular_solar",
    category: "solar",
    sign: "gemini",
    degree: 11,
    saros: 128,
    isPenumbral: false,
    title: "Annular Solar Eclipse in Gemini",
    essence: "Dialogue Begins",
    interpretation:
      "A 'Ring of Fire' eclipse in Gemini initiates new chapters in communication, learning, and connection. This eclipse opens doors for fresh dialogues, writing projects, and intellectual exploration as we enter a new decade.",
    themes: ["communication", "dialogue", "learning", "connection", "new chapter"],
    portalId: "2030-spring",
    portalPosition: "opener",
  },
  {
    id: "2030-06-15",
    date: "2030-06-15",
    timeUtc: "18:34",
    type: "partial_lunar",
    category: "lunar",
    sign: "sagittarius",
    degree: 25,
    saros: 140,
    isPenumbral: false,
    title: "Partial Lunar Eclipse in Sagittarius",
    essence: "Beliefs Released",
    interpretation:
      "This Sagittarius lunar eclipse illuminates beliefs and philosophies that have guided us. Some may be released as outdated; others revealed as true north stars. The partial nature allows for nuanced adjustment rather than dramatic transformation.",
    themes: ["beliefs", "philosophy", "release", "truth", "adjustment"],
    portalId: "2030-spring",
    portalPosition: "closer",
  },
  {
    id: "2030-11-25",
    date: "2030-11-25",
    timeUtc: "06:51",
    type: "total_solar",
    category: "solar",
    sign: "sagittarius",
    degree: 3,
    saros: 133,
    isPenumbral: false,
    title: "Total Solar Eclipse in Sagittarius",
    essence: "Vision Quest",
    interpretation:
      "A magnificent total solar eclipse in Sagittarius visible across southern Africa and Australia. This eclipse initiates a powerful new cycle of expansion, learning, and spiritual seeking. What grand adventure calls you forward?",
    themes: ["vision", "adventure", "expansion", "seeking", "initiation"],
    portalId: "2030-fall",
    portalPosition: "opener",
  },
  {
    id: "2030-12-09",
    date: "2030-12-09",
    timeUtc: "22:28",
    type: "penumbral_lunar",
    category: "lunar",
    sign: "gemini",
    degree: 18,
    saros: 145,
    isPenumbral: true,
    title: "Penumbral Lunar Eclipse in Gemini",
    essence: "Mind Clearing",
    interpretation:
      "The final eclipse of the decade arrives as a gentle penumbral lunar eclipse in Gemini. This subtle eclipse clears mental clutter and outdated thought patterns, preparing the mind for the new adventures initiated by the solar eclipse.",
    themes: ["clarity", "mind", "clearing", "preparation", "subtlety"],
    portalId: "2030-fall",
    portalPosition: "closer",
  },
];

/**
 * Eclipse Portals 2020-2030.
 *
 * Portals are the ~2-week windows between paired eclipses in the same season.
 * Most portals have 2 eclipses; some have 3 (extended portals).
 */
export const PORTALS: EclipsePortal[] = [
  // 2020
  {
    id: "2020-winter",
    name: "Winter 2020 Eclipse Portal",
    openingDate: "2020-01-10",
    closingDate: "2020-01-10",
    eclipseIds: ["2020-01-10"],
    isExtended: false,
    axis: "Cancer-Capricorn",
    essence: "Emotional Restructuring",
    interpretation:
      "A single-eclipse portal (the paired solar eclipse occurred in late December 2019). This Cancer lunar eclipse continues the final act of the Cancer-Capricorn eclipse cycle, restructuring our emotional foundations.",
    themes: ["emotion", "structure", "foundation", "completion"],
  },
  {
    id: "2020-summer",
    name: "Summer 2020 Eclipse Portal",
    openingDate: "2020-06-05",
    closingDate: "2020-06-21",
    eclipseIds: ["2020-06-05", "2020-06-21"],
    isExtended: false,
    axis: "Gemini-Sagittarius",
    essence: "Truth & Home",
    interpretation:
      "This portal bridges belief systems and emotional security, with the solar eclipse falling on the Summer Solstice. A powerful time for questioning truths while establishing new emotional foundations.",
    themes: ["truth", "home", "solstice", "foundation", "beliefs"],
  },
  {
    id: "2020-fall",
    name: "Fall 2020 Eclipse Portal",
    openingDate: "2020-11-30",
    closingDate: "2020-12-14",
    eclipseIds: ["2020-11-30", "2020-12-14"],
    isExtended: false,
    axis: "Gemini-Sagittarius",
    essence: "Mind & Meaning",
    interpretation:
      "This portal continues the Gemini-Sagittarius axis activation, transforming how we think and what we believe. A potent time for releasing old mental patterns and embracing expanded worldviews.",
    themes: ["mind", "meaning", "beliefs", "expansion", "communication"],
  },

  // 2021
  {
    id: "2021-spring",
    name: "Spring 2021 Eclipse Portal",
    openingDate: "2021-05-26",
    closingDate: "2021-06-10",
    eclipseIds: ["2021-05-26", "2021-06-10"],
    isExtended: false,
    axis: "Gemini-Sagittarius",
    essence: "Revelation & Voice",
    interpretation:
      "The final act of the Gemini-Sagittarius eclipse cycle brings powerful revelations about truth and communication. A Blood Moon followed by a 'Ring of Fire' creates intensity around knowledge and expression.",
    themes: ["revelation", "voice", "truth", "communication", "completion"],
  },
  {
    id: "2021-fall",
    name: "Fall 2021 Eclipse Portal",
    openingDate: "2021-11-19",
    closingDate: "2021-12-04",
    eclipseIds: ["2021-11-19", "2021-12-04"],
    isExtended: false,
    axis: "Taurus-Scorpio",
    essence: "Value & Faith",
    interpretation:
      "This portal initiates the Taurus-Scorpio eclipse cycle, bridging material values and spiritual depth. The longest partial lunar eclipse in centuries opens a powerful two-week window of transformation.",
    themes: ["values", "faith", "transformation", "resources", "depth"],
  },

  // 2022
  {
    id: "2022-spring",
    name: "Spring 2022 Eclipse Portal",
    openingDate: "2022-04-30",
    closingDate: "2022-05-16",
    eclipseIds: ["2022-04-30", "2022-05-16"],
    isExtended: false,
    axis: "Taurus-Scorpio",
    essence: "Foundation & Release",
    interpretation:
      "This portal continues the Taurus-Scorpio transformation, with a solar eclipse planting new seeds of security followed by a Blood Moon releasing deep attachments. A powerful time for resource restructuring.",
    themes: ["foundation", "release", "resources", "transformation", "security"],
  },
  {
    id: "2022-fall",
    name: "Fall 2022 Eclipse Portal",
    openingDate: "2022-10-25",
    closingDate: "2022-11-08",
    eclipseIds: ["2022-10-25", "2022-11-08"],
    isExtended: false,
    axis: "Taurus-Scorpio",
    essence: "Power & Values",
    interpretation:
      "The final portal of the Taurus-Scorpio cycle brings culmination to themes of values versus desires, stability versus transformation. Deep psychological work completes as we release old attachments.",
    themes: ["power", "values", "culmination", "transformation", "release"],
  },

  // 2023
  {
    id: "2023-spring",
    name: "Spring 2023 Eclipse Portal",
    openingDate: "2023-04-20",
    closingDate: "2023-05-05",
    eclipseIds: ["2023-04-20", "2023-05-05"],
    isExtended: false,
    axis: "Aries-Libra",
    essence: "Identity & Depth",
    interpretation:
      "This portal initiates the Aries-Libra eclipse cycle with a rare hybrid eclipse. The transition between eclipse series creates unique intensity around identity, relationship, and psychological transformation.",
    themes: ["identity", "depth", "initiation", "transition", "relationship"],
  },
  {
    id: "2023-fall",
    name: "Fall 2023 Eclipse Portal",
    openingDate: "2023-10-14",
    closingDate: "2023-10-28",
    eclipseIds: ["2023-10-14", "2023-10-28"],
    isExtended: false,
    axis: "Aries-Libra",
    essence: "Balance & Grounding",
    interpretation:
      "This portal continues the Aries-Libra activation while touching Taurus themes. A 'Ring of Fire' in Libra followed by a Taurus lunar eclipse bridges relationship and resource matters.",
    themes: ["balance", "grounding", "relationship", "values", "partnership"],
  },

  // 2024
  {
    id: "2024-spring",
    name: "Spring 2024 Eclipse Portal",
    openingDate: "2024-03-25",
    closingDate: "2024-04-08",
    eclipseIds: ["2024-03-25", "2024-04-08"],
    isExtended: false,
    axis: "Aries-Libra",
    essence: "Bold Becoming",
    interpretation:
      "This highly anticipated portal features the 'Great North American Eclipse' on April 8th. A subtle penumbral opener prepares for the dramatic total solar eclipse, creating a potent window for identity transformation.",
    themes: ["identity", "courage", "becoming", "initiation", "self-discovery"],
  },
  {
    id: "2024-fall",
    name: "Fall 2024 Eclipse Portal",
    openingDate: "2024-09-18",
    closingDate: "2024-10-02",
    eclipseIds: ["2024-09-18", "2024-10-02"],
    isExtended: false,
    axis: "Pisces-Virgo",
    essence: "Dreams & Justice",
    interpretation:
      "This portal bridges Pisces mysticism with Libra justice, creating a unique mix of spiritual release and relational initiation. Dreams are illuminated and released as new social contracts form.",
    themes: ["dreams", "justice", "spirituality", "relationship", "balance"],
  },

  // 2025
  {
    id: "2025-spring",
    name: "Spring 2025 Eclipse Portal",
    openingDate: "2025-03-14",
    closingDate: "2025-03-29",
    eclipseIds: ["2025-03-14", "2025-03-29"],
    isExtended: false,
    axis: "Virgo-Pisces",
    essence: "Service & Self",
    interpretation:
      "This portal activates the Virgo-Pisces axis and continues Aries themes. A Blood Moon in Virgo followed by an Aries solar eclipse bridges healing service with self-assertion.",
    themes: ["service", "self", "healing", "identity", "courage"],
  },
  {
    id: "2025-fall",
    name: "Fall 2025 Eclipse Portal",
    openingDate: "2025-09-07",
    closingDate: "2025-09-21",
    eclipseIds: ["2025-09-07", "2025-09-21"],
    isExtended: false,
    axis: "Virgo-Pisces",
    essence: "Mystic Service",
    interpretation:
      "This portal brings culmination to spiritual themes with a Pisces Blood Moon, followed by initiation of new service cycles with a Virgo solar eclipse at the critical 29th degree. Deep completion and new practical wisdom.",
    themes: ["mysticism", "service", "completion", "wisdom", "healing"],
  },

  // 2026
  {
    id: "2026-winter",
    name: "Winter 2026 Eclipse Portal",
    openingDate: "2026-02-17",
    closingDate: "2026-03-03",
    eclipseIds: ["2026-02-17", "2026-03-03"],
    isExtended: false,
    axis: "Aquarius-Leo",
    essence: "Vision & Healing",
    interpretation:
      "This portal initiates the Aquarius-Leo axis with a 'Ring of Fire' at the final degree of Aquarius, followed by a Virgo Blood Moon. Collective vision meets personal healing in this liminal window.",
    themes: ["vision", "healing", "innovation", "service", "collective"],
  },
  {
    id: "2026-summer",
    name: "Summer 2026 Eclipse Portal",
    openingDate: "2026-08-12",
    closingDate: "2026-08-28",
    eclipseIds: ["2026-08-12", "2026-08-28"],
    isExtended: false,
    axis: "Leo-Aquarius",
    essence: "Heart & Dreams",
    interpretation:
      "This magnificent portal features a total solar eclipse in Leo followed by a Pisces partial lunar eclipse. Creative self-expression and spiritual dreams interweave in this powerful two-week window.",
    themes: ["heart", "dreams", "creativity", "spirituality", "expression"],
  },

  // 2027
  {
    id: "2027-winter",
    name: "Winter 2027 Eclipse Portal",
    openingDate: "2027-02-06",
    closingDate: "2027-02-20",
    eclipseIds: ["2027-02-06", "2027-02-20"],
    isExtended: false,
    axis: "Aquarius-Leo",
    essence: "Revolution & Service",
    interpretation:
      "This portal continues the Aquarian revolutionary energy with a 'Ring of Fire' opening, followed by a gentle Virgo penumbral eclipse. Innovation meets practical service.",
    themes: ["revolution", "service", "innovation", "healing", "community"],
  },
  {
    id: "2027-summer",
    name: "Summer 2027 Eclipse Portal",
    openingDate: "2027-07-18",
    closingDate: "2027-08-02",
    eclipseIds: ["2027-07-18", "2027-08-02"],
    isExtended: false,
    axis: "Capricorn-Cancer",
    essence: "Authority & Heart",
    interpretation:
      "This portal bridges Capricorn authority themes with Leo heart-centered expression. A subtle penumbral opener prepares for the spectacular total solar eclipse in Leo visible across multiple continents.",
    themes: ["authority", "heart", "leadership", "creativity", "structure"],
  },

  // 2028
  {
    id: "2028-winter",
    name: "Winter 2028 Eclipse Portal",
    openingDate: "2028-01-12",
    closingDate: "2028-01-26",
    eclipseIds: ["2028-01-12", "2028-01-26"],
    isExtended: false,
    axis: "Cancer-Capricorn",
    essence: "Home & Future",
    interpretation:
      "This portal activates the Cancer-Capricorn axis, bridging emotional security themes with Aquarian innovation. A Cancer lunar eclipse opens to an Aquarian solar eclipse, connecting roots to revolution.",
    themes: ["home", "future", "security", "innovation", "belonging"],
  },
  {
    id: "2028-summer",
    name: "Summer 2028 Eclipse Portal",
    openingDate: "2028-07-06",
    closingDate: "2028-07-22",
    eclipseIds: ["2028-07-06", "2028-07-22"],
    isExtended: false,
    axis: "Capricorn-Cancer",
    essence: "Structure & Roots",
    interpretation:
      "This portal brings the Cancer-Capricorn axis into focus with a Capricorn lunar eclipse followed by a Cancer total solar eclipse at the critical 29th degree. Deep transformation of home and career themes.",
    themes: ["structure", "roots", "career", "home", "completion"],
  },

  // 2029
  {
    id: "2029-winter",
    name: "Winter 2029 Eclipse Portal",
    openingDate: "2029-01-14",
    closingDate: "2029-01-14",
    eclipseIds: ["2029-01-14"],
    isExtended: false,
    axis: "Capricorn-Cancer",
    essence: "Authority Renewed",
    interpretation:
      "A single-eclipse portal following the Cancer Blood Moon of 2028. This Capricorn solar eclipse establishes new structures and goals as the Cancer-Capricorn cycle continues.",
    themes: ["authority", "goals", "structure", "initiation"],
  },
  {
    id: "2029-summer",
    name: "Summer 2029 Eclipse Portal",
    openingDate: "2029-06-12",
    closingDate: "2029-06-26",
    eclipseIds: ["2029-06-12", "2029-06-26"],
    isExtended: false,
    axis: "Gemini-Sagittarius",
    essence: "Mind & Legacy",
    interpretation:
      "This portal bridges Gemini communication with Capricorn achievement. A Gemini solar eclipse initiates new mental pursuits while a Capricorn Blood Moon illuminates what we've built.",
    themes: ["mind", "legacy", "communication", "achievement", "transformation"],
  },
  {
    id: "2029-winter-2",
    name: "Winter 2029-30 Eclipse Portal",
    openingDate: "2029-12-05",
    closingDate: "2029-12-20",
    eclipseIds: ["2029-12-05", "2029-12-20"],
    isExtended: false,
    axis: "Sagittarius-Gemini",
    essence: "Faith & Completion",
    interpretation:
      "This end-of-year portal closes the decade with Sagittarian faith and Gemini completion. A solar eclipse renews our vision while a Blood Moon at 29° Gemini completes a cycle of learning.",
    themes: ["faith", "completion", "vision", "truth", "wisdom"],
  },

  // 2030
  {
    id: "2030-spring",
    name: "Spring 2030 Eclipse Portal",
    openingDate: "2030-06-01",
    closingDate: "2030-06-15",
    eclipseIds: ["2030-06-01", "2030-06-15"],
    isExtended: false,
    axis: "Gemini-Sagittarius",
    essence: "New Dialogue",
    interpretation:
      "The first portal of the new decade initiates fresh cycles of communication and belief. A Gemini 'Ring of Fire' opens new conversations while a Sagittarian partial eclipse adjusts our philosophies.",
    themes: ["dialogue", "beliefs", "communication", "philosophy", "new chapter"],
  },
  {
    id: "2030-fall",
    name: "Fall 2030 Eclipse Portal",
    openingDate: "2030-11-25",
    closingDate: "2030-12-09",
    eclipseIds: ["2030-11-25", "2030-12-09"],
    isExtended: false,
    axis: "Sagittarius-Gemini",
    essence: "Grand Vision",
    interpretation:
      "The final eclipse portal of our data range brings a spectacular total solar eclipse in Sagittarius followed by a gentle Gemini penumbral eclipse. A powerful ending that seeds grand visions for the future.",
    themes: ["vision", "adventure", "expansion", "clarity", "future"],
  },
];
