/**
 * Mirror templates (1221, 1331, 12321, etc.)
 *
 * Generated by scripts/generate-templates.ts
 */

import type { BaseTemplate } from "../../types";

const templates: BaseTemplate[] = [
  // Templates will be populated by generation script
];

export default templates;
