/**
 * Repetition templates (111, 222, 333, etc.)
 *
 * Generated by scripts/generate-templates.ts
 */

import type { BaseTemplate } from "../../types";

const templates: BaseTemplate[] = [
  // Templates will be populated by generation script
];

export default templates;
